<template>
  <div class="helppage">
    <h4>This game is a slightly modified bingo game</h4>
    <ul>
        <div class="heading">Rules : </div>
        <li>Player will be given a 5 x 5 grid with numbers ranging from 0 to 99</li>
        <li>These numbers will be randomly generated by the game</li>
        <li>Each player should select a number on his/her turn</li>
        <li>Other player's selected values will automatically get highlighted</li>
        <li>If a complete row (or) column (or) diagonal of numbers are selected, then the player has achieved a milestone</li>
        <li>Player has to achieve atleast 5 milestones to win the game</li>
    </ul>
  </div>
</template>

<script>
export default {

}
</script>

<style>
.heading{
    transform: translateX(-30px);
}
ul{
    text-align: justify;
    padding-right:30px;
}
.helppage{
    overflow-y:scroll ;
}
</style>