# This is a basic workflow to help you get started with Actions

name: Push To Heroku

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name : Build App
      run : |
        npm install
        npm run build
        npm run removeDistFromIgnored
    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_OAUTH_TOKEN }}@git.heroku.com/my-bingo-game.git
        git fetch --all --unshallow
        git filter-branch -- --all
    - name: Deploy to Heroku
      run: |
        git push heroku master -f
    # Runs a single command using the runners shell
#     - name: Push To Heroku
#       env:
#         HEROKU_OAUTH_TOKEN: ${{  }}
#         HEROKU_APP_NAME: "my-bingo-game"
#       if: github.ref == 'refs/heads/master' && job.status == 'success'
#       run: git push --force https://heroku:$HEROKU_OAUTH_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git master:master

